##
# Raycaster
#
# @file
# @version 0.1

raycaster-debug:
	gcc raycaster.c -o raycaster -lm -lSDL2 -g

raycaster-release:
	gcc raycaster.c -o raycaster -lm -lSDL2 -O3

backup-raycaster:
	gcc backup_raycaster.c -o backup_raycaster -lm -lSDL2
	

# end
